# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kristinavilyams.com
title: Kristina Vilyams
email: kristinavilyams@gmail.com
author: Kristina Vilyams
description: Kristina Vilyams is a multidisciplinary creative designer at the intersection of fashion, art and performance. 
copyright: 'Copyright &copy; 2023 Kristina Vilyams. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://twitter.com/SBootstrap
    img: instagram
  - title: pinterest
    url: https://github.com/IronSummitMedia/startbootstrap
    img: pinterest
  - title: linkedin
    url: https://github.com/IronSummitMedia/startbootstrap
    img: linkedin
