# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kristinavilyams.com
title: Kristina Vilyams
email: kristinavilyams@gmail.com
author: Kristina Vilyams
description: Kristina Vilyams is a multidisciplinary creative designer at the intersection of fashion, art and performance. 
copyright: 'Copyright &copy; 2023 Kristina Vilyams. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/kristinavilyams/
    img: instagram.png
  - title: tiktok
    url: https://www.tiktok.com/@kristinavilyams/
    img: tiktok.png
  - title: linkedin
    url: https://www.linkedin.com/in/kristinavilyams/
    img: linkedin.png
  - title: youtube
    url: https://www.youtube.com/channel/UC-XdUWe4yQVmML7Gy6UUhdA
    img: youtube.png
    
articles:
#  - title: meta
#    url: https://www.facebook.com
#    img: meta.png
  - title: ballet-season
    url: https://www.ballet-season.com/good-brands/good-brands-with-ui/ux-designer-kristina-vilyams-pz7ls?fbclid=IwAR2gB3LUxJUVQHhQGk78IrSEqglLekn6yquNZicAtNyg3KazwFNhQNahJ1A
    img: ballet-season.png
  - title: architectural-digest
    url: architecturaldigest.com/story/this-ux-designer-is-re-creating-iconic-design-pieces-for-your-selfies
    img: architectural-digest.png
  - title: lenslist
    url: https://lenslist.co/search/Kristina+Vilyams#content
    img: lenslist.png
  - title: yahoo
    url: https://sports.yahoo.com/ux-designer-creating-iconic-design-134758950.html
    img: yahoo.png

collaborations:
  - title: ballet-season
    url: https://www.ballet-season.com/good-brands/good-brands-with-ui/ux-designer-kristina-vilyams-pz7ls?fbclid=IwAR2gB3LUxJUVQHhQGk78IrSEqglLekn6yquNZicAtNyg3KazwFNhQNahJ1A
    img: ballet-season.png