# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kristinavilyams.com
title: Kristina Vilyams
email: kristinavilyams@gmail.com
author: Kristina Vilyams
description: Kristina Vilyams is a multidisciplinary creative designer at the intersection of fashion, art and performance. 
copyright: 'Copyright &copy; 2023 Kristina Vilyams. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/kristinavilyams/
    img: instagram.png
  - title: tiktok
    url: https://www.tiktok.com/@kristinavilyams/
    img: tiktok.png
  - title: linkedin
    url: https://www.linkedin.com/in/kristinavilyams/
    img: linkedin.png
  - title: youtube
    url: https://www.youtube.com/channel/UC-XdUWe4yQVmML7Gy6UUhdA
    img: youtube.png
